#include "gba.h"
#include <stdio.h>
#include "logic.h"
#include "draw.h"
#include "images/sprites.h"
#include "images/puppy1.h"
#include "images/universe.h"
#include "images/gameState1.h"
#include "images/paddlePicture.h"
#include "images/yellowBrick.h"
#include "images/redBrick.h"
#include "images/blueBrick.h"
#include "images/ballPicture.h"
#include "images/heartPicture.h"
#include "images/starPicture.h"
#include "images/winGame.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);
//void drawLevel(AppState* state);
// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.

    drawImageDMA(0, 0, GAMESTATE1_WIDTH, GAMESTATE1_HEIGHT, gameState1);
    waitForVBlank();
    drawPaddle(state->paddle.row, state->paddle.col, GREEN);
    char buffer[51]; // draw the score
    sprintf(buffer, "Score: %d", state->score);
    drawString(10, 143, buffer, BLUE);
    for (int i = 0; i < 24; i++) {
        if (i < 8) {
            drawImageDMA(state->brick[i].row, state->brick[i].col, BLUEBRICK_WIDTH, BLUEBRICK_HEIGHT, blueBrick);
        } else if (i < 16) {
            drawImageDMA(state->brick[i].row, state->brick[i].col, REDBRICK_WIDTH, REDBRICK_HEIGHT, redBrick);
        } else {
            drawImageDMA(state->brick[i].row, state->brick[i].col, YELLOWBRICK_WIDTH, YELLOWBRICK_HEIGHT, yellowBrick);
        }

    }
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    if (state->ballReleased == 1) {
        unDrawString(115, 70, 105, 10, gameState1);
        unDrawString(130, 45, 153, 10, gameState1);
    }
    unDrawBall(state->ball.row, state->ball.col, gameState1);
    unDrawPaddle(state->paddle.row, state->paddle.col, gameState1);
    unDrawScore(143, 50, gameState1);
    unDrawHeart(143, 200, gameState1);


    for (int i = 0; i < 24; i++) {
        if (state->brick[i].value == 0) {
            unDrawBrick(state->brick[i].row, state->brick[i].col, state->brick[i].width, state->brick[i].height, gameState1);
        }
    }
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    //starting the ball
    if (state->ballReleased == 1) {
        drawImageDMA(100, 120, BALLPICTURE_WIDTH, BALLPICTURE_HEIGHT, ballPicture);
        drawCenteredString(120, 120, 2, 2, "Press B to Start!", YELLOW);
        drawCenteredString(120, 135, 2, 2, "Press RESET to Reset Game", YELLOW);
    } else {
        drawImageDMA(state->ball.row, state->ball.col, BALLPICTURE_WIDTH, BALLPICTURE_HEIGHT, ballPicture);
    }
    //draw paddle
    drawImageDMA(state->paddle.row, state->paddle.col, PADDLEPICTURE_WIDTH, PADDLEPICTURE_HEIGHT, paddlePicture);

    // draw the score
    char buffer[51];
    sprintf(buffer, "Score: %d", state->score);
    drawString(10, 143, buffer, BLUE);

    //draw the heart
    for (int i = 0; i < state->heart; i++) {
        drawImageDMA(143, 200 + i*12, HEARTPICTURE_WIDTH, HEARTPICTURE_HEIGHT, heartPicture);
    }
}

// This function will be used to draw the starting state of the game.
void drawGameStartState(void) {
    drawImageDMA(0, 0, UNIVERSE_WIDTH, UNIVERSE_HEIGHT, universe);
    waitForVBlank();
    drawCenteredString(120, 60, 2, 2, "WELCOME TO THE", GREEN);
    drawCenteredString(120, 80, 2, 2, "GALAXY OF BRICKS", GREEN);
    drawCenteredString(120, 130, 2, 2, "Press START to Start Game", GREEN);
}

// This function will be used to draw the losing state of the game.
void drawGameOverState(AppState *state) {
    drawImageDMA(0, 0, WINGAME_WIDTH, WINGAME_HEIGHT, winGame);
    waitForVBlank();
    drawCenteredString(120, 50, 2, 2, "Game Over!!", GREEN);

    // draw the high score
    char buffer1[51];
    sprintf(buffer1, "Your Score: %d", state->score);
    drawCenteredString(120, 80, 2, 2, buffer1, YELLOW);
    drawCenteredString(120, 120, 2, 2, "Press SELECT to play a NEW GAME", GREEN);
    drawCenteredString(120, 140, 2, 2, "Developed by TU NGUYEN", RED);
    //    delay(500);
    UNUSED(state);
}

// This function will be used to draw the winning state of the game.
void drawWinGame(AppState *state) {
    drawImageDMA(0, 0, WINGAME_WIDTH, WINGAME_HEIGHT, winGame);
    waitForVBlank();
    drawImageDMA(15, 110, STARPICTURE_WIDTH, STARPICTURE_HEIGHT, starPicture);
    drawCenteredString(120, 50, 2, 2, "GREAT WORK!", GREEN);
    drawCenteredString(120, 70, 2, 2, "YOU HAVE CONQUERED", GREEN);
    drawCenteredString(120, 90, 2, 2, "THE UNIVERSE OF BRICKS", GREEN);
    drawCenteredString(120, 120, 2, 2, "Press SELECT to try another game!", GREEN);
    drawCenteredString(120, 140, 2, 2, "Developed by TU NGUYEN", RED);
    UNUSED(state);
}